### ISSUE TITLE
Documentation Link is broken

### ISSUE THREAD

**Issue by gtnarg** [mvel/mvel#101]
https://en.wikisource.org/wiki/MVEL_Language_Guide no longer works.

Is this documentation available elsewhere?

**Comment by jiakuan** [comment]
I have arranged the documentation into markdown format and hosted a HTML version here: http://mvel.documentnode.com/

Please feel to fork from here: https://github.com/jiakuan/mvel-doc in case anything in the doc needs to be improved.

**Comment by VEnis** [comment]
Original link was moved to https://en.wikibooks.org/wiki/Transwiki:MVEL_Language_Guide

**Comment by cy6erGn0m** [comment]
Any chance for this to be fixed?

**Comment by kovax** [comment]
@jiakuan Please correct the link in the Description of this repository as well.

**Comment by jiakuan** [comment]
@kovax I think only the owner of this repo can change the description.

If there is no better solution, I plan to maintain a good documentation page for MVEL. When I have a chance, I will improve the layout etc to make it more readable and easier to navigate.

**Comment by kovax** [comment]
@jiakuan I am sorry Jake, I just assumed your were one of the owners :) I really appreciate your effort on this.

@mariofusco Please correct the link in the Description of this repository so Jake's contribution can be found much easier.

**Comment by mariofusco** [comment]
Done. Thanks a lot @jiakuan
