### ISSUE TITLE
how to get variables and functions list from compiled expression 

### ISSUE THREAD

**Issue by xbkaishui** [mvel/mvel#118]
Hi Someone can tell me how to get variables and functions from mvel expression 
for example: 
String  exp = "Math.ceil( (double) x / 3 ) + bb";

Thanks

**Comment by jonahglover** [comment]
@xbkaishui did you ever find a solution for this?

**Comment by xbkaishui** [comment]
Yes, I have digged into the source code, You can use below examples: 

```
 public Set<String> analysisInputs(String exp){
        ParserContext pCtx = ParserContext.create();
        MVEL.analysisCompile(exp, pCtx);
        Map<String, Class> inputsMap = pCtx.getInputs();
        return inputsMap.keySet();
    }
```

**Comment by xbkaishui** [comment]
No problem.

**Comment by rohts-patil** [comment]
@xbkaishui What about nested variables? As in let's say I have something like:-

`int name = person.firstName + person.lastName;`

When I run this through  `MVEL.analysisCompile(exp, pCtx);` , I get the output as person only. 

Is there any way to get the output as person.firstName and person.lastName as they both are different variables?
