### ISSUE TITLE
[Question] Is MVEL evaluation case sensitive ? 

### ISSUE THREAD

**Issue by senthilporunan** [mvel/mvel#127]
I am using MVEL for evaluate java object. 

Working:
print org.mvel2.MVEL.eval("?getWrapIn.getAccountNumber", request) ===> "12345"

Not Working:
print org.mvel2.MVEL.eval("?getwrapin.getaccountnumber", request) ===> null

Is there any workaround to make it is behaving same way irrespective of cases.

**Comment by mariofusco** [comment]
No way. Mvel is case senstive (as any respectful language should be).
