### ISSUE TITLE
Add an option to treat unresolvable identifier as null for safety

### ISSUE THREAD

**Issue by quaff** [mvel/mvel#172]
With some use case, expressions are defined with unbound context, I wish mvel cound provide an option treat undefined identifier as null like map.get(), and this option is disabled by default.

**Comment by quaff** [comment]
https://github.com/mvel/mvel/blob/master/src/main/java/org/mvel2/optimizers/impl/refl/ReflectiveAccessorOptimizer.java#L703
Add a flag to return null instead of throw exception.

**Comment by quaff** [comment]
ping

**Comment by MalcolmOdd** [comment]
Hi quaff,
If I were you I would consider submitting this as a pull request. It would however have to cover the following:
- Support in the ASM optimizer, which kicks in after a certain number of runs (the code your reference is in the safe reflective optimizer)
- Unit test to demonstrate it with both accessor optimizers
Also what will happen when the null value enters further calculations, like arithmetic or logical operators?

**Comment by quaff** [comment]
@MalcolmOdd I need to confirm it is acceptable by project owner before submitting a pull request.
I think it's a small change, It only fall back unresolvable identifier to null-valued identifier which is legal already, WDYT?

**Comment by MalcolmOdd** [comment]
@quaff  Maybe you should provide examples in the form of unit tests. We had a similar concern at my previous job: we used to keep mvel formulas in configuration file and would use some entities that could be null. The answer was to use the square brackets instead of the dot operator. The object having the potentially null attributes must be added to the context rather than being the context itself. Consider the following:
```java
  public void testIssue172() throws Throwable {
      Map<String, Object> context = new HashMap<String, Object>();
      context.put("userData", Collections.singletonMap("xp", "100"));
      Serializable xpExpr = MVEL.compileExpression("userData['xp']");
      Assert.assertEquals("100", MVEL.executeExpression(xpExpr, context));
      Serializable levelExpr = MVEL.compileExpression("userData['level']");
      Assert.assertEquals(null, MVEL.executeExpression(levelExpr, context));
  }
```

**Comment by quaff** [comment]
Construct a safe hash map as workaround
```java
public class SafeHashMap<K, V> extends HashMap<K, V> {

  @Override
  public boolean containsKey(Object key) {
   return true;
  }

}
```
