### ISSUE TITLE
in use ,I need division by zero,result is zero

### ISSUE THREAD

**Issue by kongkong4556** [mvel/mvel#209]
According to my Application Scenarios,  when division by zero, need to return 0,not error, is there any solutions to solve the problem? exp： 5/0 =0  1+8/0 =1

**Comment by mariofusco** [comment]
Sorry but yes, the only reasonable solution is reviewing your application scenarios and make it work with proper math. What you're asking is like saying that you have a use case where you want 2+2=5

**Comment by kongkong4556** [comment]
Can mvel support the divide operator overloading? thanks

**Comment by kongkong4556** [comment]
Can mvel support the divide operator overloading? thanks

**Comment by MalcolmOdd** [comment]
@kongkong4556  you could change the expression to something like "x != 0 ? 5 / x : 0".  Sounds simpler than overloading the maths.

**Comment by kongkong4556** [comment]
Thank you for your answer, but in my system, the formula looks like math formula,for example 5/x/(3+4/w)+6/y+7,I can't change every part of the formula  to something like "x != 0 ? 5 / x : 0"  ,it can cause lots of other works










At 2019-10-22 19:57:26, "MalcolmOdd" <notifications@github.com> wrote:

@kongkong4556 you could change the expression to something like "x != 0 ? 5 / x : 0". Sounds simpler than overloading the maths.
