### ISSUE TITLE
MVEL expression evaluation bug: Should this be getValue(ctx, elCtx, vars) instead of getValue(elCtx, elCtx, vars)?

### ISSUE THREAD

**Issue by mjh0907** [mvel/mvel#226]
https://github.com/mvel/mvel/blob/0e68fc6b5fcf67c1bc88069633ddb254fe4ded67/src/main/java/org/mvel2/optimizers/impl/refl/nodes/ThisValueAccessor.java#L29

I am seeing an issue when evaluating an expression which gives incorrect result. The expression is foo.bar, where foo is a map and bar is a key in the map. It's very tricky to reproduce.

However, after changing the first elCtx to ctx, it seems to work. This change makes more sense to me and it seems also consistent with other accessors (using ctx instead of elCtx).

Can anyone shed some light on this? Thanks. @mikebrock @jlopez @machaval @benbennett @harawata

**Comment by mjh0907** [comment]
@MalcolmOdd Thanks.

**Comment by MalcolmOdd** [comment]
Hi @mjh0907 ,
Can you provide and example test?
I tried the following and it succeeded:
```java
  public void testMVEL226() {
      Map<String, String> foo = new HashMap();
      foo.put("bar", "baz");
      OptimizerFactory.setDefaultOptimizer("reflective");
      Serializable compiledExpression = MVEL.compileExpression("this.bar");
      VariableResolverFactory factory = new MapVariableResolverFactory(new HashMap<String, Object>());
      assertEquals("baz", MVEL.executeExpression(compiledExpression, foo, factory, String.class));
    }
```
I think maybe the code is not passing ctx because the expressions explicitly specifies "this" so global variables should be disregarded.

**Comment by mjh0907** [comment]
@MalcolmOdd  Thanks a lot for the help!

Please see my test case below:
```
import java.io.Serializable;
import java.util.HashMap;
import java.util.Map;
import org.apache.avro.Schema;
import org.apache.avro.generic.GenericData;
import org.apache.avro.generic.GenericRecord;
import org.mvel2.integration.PropertyHandler;
import org.mvel2.integration.PropertyHandlerFactory;
import org.testng.annotations.Test;

import org.mvel2.MVEL;
import org.mvel2.integration.VariableResolverFactory;
import org.mvel2.integration.impl.MapVariableResolverFactory;
import org.mvel2.optimizers.OptimizerFactory;
import static org.testng.Assert.*;
  @Test
  public void testMVEL2261() {
    Map<String, String> foo = new HashMap();
    //foo.put("bar", "baz");
    OptimizerFactory.setDefaultOptimizer("reflective");
    Serializable compiledExpression = MVEL.compileExpression("this.bar");
    VariableResolverFactory factory = new MapVariableResolverFactory(new HashMap<String, Object>());
    //assertEquals("baz", MVEL.executeExpression(compiledExpression, foo, factory, String.class));
    Map<String, String> foo2 = new HashMap();
    foo2.put("bar", "baz2");
    assertEquals("baz2", MVEL.executeExpression(compiledExpression, foo2, factory, String.class));
  }
  @Test
  public void testMVEL226() {
    String schemaFile = "{ \"name\" : \"Profile\", \"type\" : \"record\", \"fields\" : ["
        + "   { \"name\" : \"testMap\", "
        + "     \"type\" : {"
        + "          \"type\" : \"map\", \"values\" : \"string\""
        + "     } "
        + "   } "
        + "  ] "
        + "}";
    Schema schema =  Schema.parse(schemaFile);
    GenericRecord firstRecord = new GenericData.Record(schema);
    // the map value for the first record, note that it does NOT have the target key 'testKey'
    Map<String, String> firstRecordValue = new HashMap();
    firstRecord.put("testMap", firstRecordValue);

    OptimizerFactory.setDefaultOptimizer(OptimizerFactory.SAFE_REFLECTIVE);


    // test case 1: Bug reproduced
    Serializable compiledExpression = MVEL.compileExpression("testMap.testKey");
    // test case 2: Bug reproduced
    // Serializable compiledExpression = MVEL.compileExpression("testMap.testKey != null? testMap.testKey : null;\n");
    // test case 3: Working fine, the only different between case 2 and 3 is changing the first testMap.testKey to testMap['testKey']
    // Serializable compiledExpression = MVEL.compileExpression("testMap['testKey'] != null? testMap.testKey : null;\n");
    // test case 4: Working fine
    // Test case 3 and 4 succeed, because they're not using ThisValueAccessor
    // Serializable compiledExpression = MVEL.compileExpression("isPresent = def (x) { x != null ? true : false }; isPresent(testMap.testKey) ? testMap.testKey : null;\n");
    VariableResolverFactory factory = new MapVariableResolverFactory(new HashMap<String, Object>());
    PropertyHandlerFactory.registerPropertyHandler(GenericRecord.class, GenericRecordPropertyHandler.INSTANCE);

    // Evaluate the first record using the compiled MVEL expression, this is the direct root cause of the issue
    String res = MVEL.executeExpression(compiledExpression, firstRecord, factory, String.class);
    assertEquals(res, null);

    Map<String, String> secondRecordValue = new HashMap();
    // the map value for the second record, note that it DOES have the target key 'testKey'
    secondRecordValue.put("testKey", "testMapValue");
    GenericRecord secondRecord = new GenericData.Record(schema);
    secondRecord.put("testMap", secondRecordValue);

    // This assert will fail, there're 3 ways to fix this:
    // 1. Comment out the previous MVEL.executeExpression()
    // 2. Recompile the MVEL expression here, but this will bring performance issue (as we should not compile for each record)
    // 3. Change the elCtx to ctx in ThisValueAccessor
    assertEquals(MVEL.executeExpression(compiledExpression, secondRecord, factory, String.class), "testMapValue");
  }
}

class GenericRecordPropertyHandler implements PropertyHandler {
  public static final GenericRecordPropertyHandler INSTANCE = new GenericRecordPropertyHandler();

  private GenericRecordPropertyHandler() { }

  @Override
  public Object getProperty(String name, Object contextObj, VariableResolverFactory variableFactory) {
    Object output = ((GenericRecord) contextObj).get(name);
    return output;
  }

  @Override
  public Object setProperty(String name, Object contextObj, VariableResolverFactory variableFactory, Object value) {
    throw new UnsupportedOperationException();
  }
}

```

**Comment by MalcolmOdd** [comment]
@mjh0907 thanks for the test. The PropertyHandler appears to make a big difference here.  
Your suggested change will solve the issue, and I was unable to find any side effect. 
However, there's something weird going on here (with or without the change): If I set a breakpoint in GenericRecordPropertyHandler.getProperty(), I see that it's called twice for the first evaluation, and one time it's with testKey (which belongs to the map, not the GenericRecord). This appears like an improper fallback when null is found. In fact, if you add a String property named testKey in the avro model and put a value for it in firstRecord, the first assertion will fail because this value will be returned. It's like "testKey" becomes a valid substitute for "testMap.testKey".
For the sake of discussion, **removing** the following line from ReflectiveAccessOptimizer at lines 702 and 1088 would also resolve the issue and not break any unit test (though it would not change that weird substitution case):
```java
        addAccessorNode(new ThisValueAccessor());
```   
I don't understand why we need a ThisValueAccessor node here: The context is already at the correct 'this' value at this time.
This will need further investigation.

**Comment by mjh0907** [comment]
@MalcolmOdd Nice catch! Seems the code "addAccessorNode(new ThisValueAccessor());
" in ReflectiveAccessOptimizer at lines 702 and 1088  were [added](https://github.com/mvel/mvel/commit/8beb826c6d920474f1a2a205c341195ae130b3f9) a few year ago. @mariofusco  Would you be able to help provide some context or suggestion on this issue? Thanks a lot!

**Comment by MalcolmOdd** [comment]
The addAccessorNode code was introduced to handle expressions like "map[key]" where both map and key are properties of the "this" object passed to MVEL. See CoreConfidenceTests.testMapAccessWithNestedProperty().
I have a potential solution where MapAccessorNest would be modified to use elCtx instead of ctx when calling the inner expression, but I have to assess the impact for other uses of the class before submitting a PR. 
BTW, in the test above, the correct behavior would be to throw a PropertyAccessException rather than return null for the first record. The "testMap.testKey" expressions refers to a non-existent property.

**Comment by mjh0907** [comment]
@MalcolmOdd  " the correct behavior would be to throw a PropertyAccessException rather than return null for the first record" This makes a lot of sense to me. Please let me know if you would like to submit a PR for both cases or not. Thanks!

**Comment by mjh0907** [comment]
@MalcolmOdd  However, in the documentation, http://mvel.documentnode.com/#maps, 

The library does support using dot to access key in a map:

 Map Access
Maps are accessed in the same way as array’s except any object can be passed as the index value. For example:

user["foobar"]
is the equivalent of the Java code:

user.get("foobar");
For Maps that use a String as a key, you may use another special syntax:

user.foobar
… Allowing you to treat the Map itself as a virtual object.

This would be a backward-incompatible change.

**Comment by MalcolmOdd** [comment]
I would not be changing the behavior: The fix would just make it consistent for the specific case here. The expression "user.foobar" is equivalent to user["foobar"] in the sense that it returns the same value but the null handling is different. In the doc you sent, please have a look at "null-safe navigation". If you write a simple case with the current implementation it will throw a PropertyAccessException:
```java
    public void testMVELNullProp() {
	Serializable compiledExpression = MVEL.compileExpression("testMap.testKey");
	VariableResolverFactory factory = new MapVariableResolverFactory(new HashMap<String, Object>());
	PropertyHandlerFactory.registerPropertyHandler(GenericRecord.class, GenericRecordPropertyHandler.INSTANCE);
	try {
	    MVEL.executeExpression(compiledExpression, Collections.singletonMap("testMap", Collections.emptyMap()),
		    factory, String.class);
	    fail("Expected PropertyAccessException");
	} catch (PropertyAccessException ex) {
	    System.out.println("Hit expected exception since testMap.testKey does not exist");
	}
    }
```
However it willl not throw an exception if you use the square brackets, or if you use "testMap.?testKey".

**Comment by MalcolmOdd** [comment]
Answering the previous question: Yes I plan to submit a PR before next week.

**Comment by mjh0907** [comment]
@MalcolmOdd Thanks a lot for the fix. Does the PR have any reviewers?

**Comment by MalcolmOdd** [comment]
Now it does (Thanks @mjh0907 , I didn't know I had to add them).

**Comment by mjh0907** [comment]
Thanks for the work. It seems that the above testMVEL226 still fails with the 2.4.7.Final release? @MalcolmOdd   @mariofusco  I'm seeing the following exception: 
[Error: could not access: testKey; in class: java.util.HashMap]
[Near : {... testMap.testKey ....}]

**Comment by MalcolmOdd** [comment]
Do you mean in your original test from Jan 3rd? As I explained on Jan 7th, it should have thrown the exception from the start since you use the dot operator ant testMap doesn't have a testKey property. Please use the square brackets if you want it to be optional.
