### ISSUE TITLE
When I adjust the position of the addend, mvel get ClassCastException

### ISSUE THREAD

**Issue by songzenghui** [mvel/mvel#249]
Here is my test code:

```java
@Test
public void testMVEL() {
    String rule1 = "30 *  x1 + 70";
    String rule2 = "70 + 30 *  x1";
    ParserContext parserContext = new ParserContext();
    Serializable compileExpression = MVEL.compileExpression(rule, parserContext);

    Map<String, Object> expressionVars = new HashMap<>();
    expressionVars.put("x1", 128.33);
    Object result = MVEL.executeExpression(compileExpression, parserContext, expressionVars);
    System.out.println(result);
}
```

When i use `rule1`, it gets right result, but when i adjust the position of addend, like `rule2`, it gets `ClassCastException`:

```
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer

	at org.mvel2.ast.IntAdd.getReducedValueAccelerated(IntAdd.java:17)
	at org.mvel2.compiler.ExecutableAccessor.getValue(ExecutableAccessor.java:42)
	at org.mvel2.MVEL.executeExpression(MVEL.java:921)
```

 Could somebody tell me why? And how to use `compileExpression` when i use expression like `rule2` ?

**Comment by songzenghui** [comment]
The MVEL's version is 2.4.4.Final.
@MalcolmOdd Sorry to bother you, but i am really confused

**Comment by MalcolmOdd** [comment]
The engine seems to assume it's adding integers based on the first term.
Interestingly, the test succeeds when adding parenthesis like this: 
```java
   70 + (30 *  x1)
```
However these parenthesis should not affect the evaluation order.
Also direct evaluation is successful:
```java
	Object result = MVEL.eval(rule2, expressionVars);
```
This looks like a bug and I'll dig further into it.

**Comment by songzenghui** [comment]
Thanks for your replying. I also found using direct evaluation is successful. 
When i change `70` to `70.0`, the `rule2` is successful.
I hope this bug can be fixed
