### ISSUE TITLE
Publish documentation

### ISSUE THREAD

**Issue by FeuTeston** [mvel/mvel#261]
Firstly, I searched for documentation on MVEL but everything I could find was on the wayback machine.
I also see the project is pretty much active (which makes me more than happy).

I understand publishing documentation has not the same priority of fixing bugs or developing new features. But it would be nice to:
- Have a README.md page.
- Eventually a github pages website (possibly with the same previous content from codehaus) as a starting point.
I do want to suggest MVEL for a project. Old timers like me knows what it is and where it is used. However I will have a hard time sending documentation for convincing the new generation or even documentation to teach users on how to use it.

I created this issue just to start "moving things". I will be happy to help. Let me know if a PR for a github pages and README.md with the same content as codehaus will be welcome and I will be happy to provide.

Thanks in advance and sorry to disturb. And thanks a million for your time!

**Comment by kovax** [comment]
@FeuTeston I got the impression from your message that you have not found any documentation. Please check this page: http://mvel.documentnode.com. It helped me out most of the cases together with the code.

**Comment by FeuTeston** [comment]
Thanks very much! That helps a lot!
