### ISSUE TITLE
Build fails under Java 17 because of module access restrictions

### ISSUE THREAD

**Issue by MalcolmOdd** [mvel/mvel#282]
Not sure it's a concern since we want to preserve compatibility with earlier Java versions, but building the mvel project with Java 17 will fail with because of more restrictive reflective access rules:
PropertyAccessTests.testMVEL308():
Unable to make public final java.lang.Object java.util.HashMap$Node.getKey() accessible: module java.base does not "opens java.util" to unnamed module @5ed828d
Note: getKey() would be available if we accessed the node as a Map.Entry but the innter class HashMap.Node is not meant to be used from the outside. We should probably try to get the method from the interface.

**Comment by mariofusco** [comment]
Fixed by https://github.com/mvel/mvel/commit/d6f9ae163e011d2959678e1881178fe25eb42f65
