### ISSUE TITLE
java.lang.StringIndexOutOfBoundsException when returning booleans within a ternary expression. 

### ISSUE THREAD

**Issue by seamusmcgonigle** [mvel/mvel#295]
This error did not occur when the same mvel is executed against MVEL1. And the error message is misleading. 

To reproduce this issue, add the following test case to ControlFlowTests.java 

```
  public void testTernary6() {
    assertEquals(true, test("false!=true ? { return true; } : false "));
  }
```

Full Stack Trace 
```
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.String.substring(String.java:1837)
	at org.mvel2.util.ErrorUtil.rewriteIfNeeded(ErrorUtil.java:22)
	at org.mvel2.compiler.AbstractParser.nextToken(AbstractParser.java:1295)
	at org.mvel2.compiler.ExpressionCompiler._compile(ExpressionCompiler.java:127)
	at org.mvel2.compiler.ExpressionCompiler.compile(ExpressionCompiler.java:68)
	at org.mvel2.tests.core.AbstractTest._test(AbstractTest.java:284)
	at org.mvel2.tests.core.AbstractTest.runSingleTest(AbstractTest.java:265)
	at org.mvel2.tests.core.AbstractTest$TestRunner.run(AbstractTest.java:253)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by MalcolmOdd** [comment]
The code was trying to output the error:
```
Error: was expecting type: java.lang.Object; but found type: <Unknown>
```
This makes sense since `return true` is not an expression but rather an instruction.
The expression message construction fails because the cursor position that points to where the error is is -1 (this should be fixed).
Apart from this, it's interesting to note that direct evaluation through `MVEL.eval(String)` does not fail but returns an array of boolean containing the value `true`

**Comment by seamusmcgonigle** [comment]
@MalcolmOdd  Thanks for looking at this. 

I'm not sure about the instruction vs expression thing. 

For example.. This gives me the same error 
`false!=true ? { System.out.println(\"one\") ; System.out.println(\"two\")} : System.out.println(\"three\")"`

While a similar if/else works fine 
`if(false!=true) {  System.out.println(\"one\") ; System.out.println(\"two\"); true} else {  System.out.println(\"three\") }"`

**Comment by MalcolmOdd** [comment]
@seamusmcgonigle the instruction block starting at the curly brace in your first example is an instruction (it cannot be evaluated as a value) so it is the same case. You can see that replacing the block with a single println call does not fail compilation:
```
"false!=true ? System.out.println(\"one\") : System.out.println(\"three\")"
```


The if/else constructs (like your second example) do not have the same requirement - only the condition part has to be an expression and ` false!=true` is an expression that evaluates to false.

**Comment by seamusmcgonigle** [comment]
Ok that makes sense to me. Thanks @MalcolmOdd
