### ISSUE TITLE
Unable to evaluate string with "-"

### ISSUE THREAD

**Issue by savannahar68** [mvel/mvel#308]
Usecase - I'm trying to do nested lookup in Map.
Issue - If the "." separated key I'm searching in the map has "-", then evaluation fails

```
public void test() {
    Map attribute = new HashMap<String, Object>() {{
        put("merchant_attributes", new HashMap<String, Object>() {{
            put("c652a326-5243-12ab-a4cd-111111", new HashMap<String, Integer>() {{
                put("num_orders", 2);
            }});
        }});
    }};

    MVEL.eval("merchant_attributes.c652a326-5243-12ab-a4cd-111111.num_orders", attribute); 
}
```

Evaluating the above test throws an error saying `[Error: could not access: c652a126; in class:`

**Comment by savannahar68** [comment]
If I replace "-" with _ in my map and in my express it works fine.

**Comment by MalcolmOdd** [comment]
The dot operator expects an identifier on the right, and identifiers cannot have dashes (as it is parsed as the minus operator) or start with a number. You can use the square brackets to access it as follows:
```
      MVEL.eval("merchant_attributes[\"c652a326-5243-12ab-a4cd-111111\"].num_orders", attribute); 
```
The underscore "_" is valid to use in an identifier

**Comment by savannahar68** [comment]
Thanks @MalcolmOdd 
Closing this.

**Comment by savannahar68** [comment]
@MalcolmOdd 
How to escape strings that are starting with a number?

```
@Test
    public void test() {
        Map attribute = new HashMap<String, Object>() {{
            put("merchant_attributes", new HashMap<String, Object>() {{
                put("c652a326-5243-12ab-a4cd-111111", new HashMap<String, Object>() {{
                    put("1652a326-5243-12ab-a4cd-111112", new HashMap<String, Integer>() {{
                        put("num_orders", 2);
                    }});
                }});
            }});
        }};
        MVEL.eval("merchant_attributes[\"c652a326-5243-12ab-a4cd-111111\"][\"1652a326-5243-12ab-a4cd-111112\"]", attribute);
    }
```


This evaluates to null, the expectation was to return a object having num_orders attribute within it.

**Comment by MalcolmOdd** [comment]
> @MalcolmOdd How to escape strings that are starting with a number?
> 
> ```
> @Test
>     public void test() {
>         Map attribute = new HashMap<String, Object>() {{
>             put("merchant_attributes", new HashMap<String, Object>() {{
>                 put("c652a326-5243-12ab-a4cd-111111", new HashMap<String, Object>() {{
>                     put("1652a326-5243-12ab-a4cd-111112", new HashMap<String, Integer>() {{
>                         put("num_orders", 2);
>                     }});
>                 }});
>             }});
>         }};
>         MVEL.eval("merchant_attributes[\"c652a326-5243-12ab-a4cd-111111\"][\"1652a326-5243-12ab-a4cd-111112\"]", attribute);
>     }
> ```
> 
> This evaluates to null, the expectation was to return a object having num_orders attribute within it.

I tried it and it evaluates to a singleton map with num_order=2
your test was ignoring the result but I changed the last line to:
``` 
      assertEquals(Collections.singletonMap("num_orders",  2), MVEL.eval("merchant_attributes[\"c652a326-5243-12ab-a4cd-111111\"][\"1652a326-5243-12ab-a4cd-111112\"]", attribute));
```
When using strings as keys using the square brackets operator, the leading numbers do not matter.

**Comment by MalcolmOdd** [comment]
> @MalcolmOdd how to escape single string with "-". I tried multiple ways with and without escaping strings with and without square brackets, but nothing works.
> 
> ```
> @Test
> public void test9() {
>     Map attribute = new HashMap<String, String>() {{
>         put("merchant-attributes", "abc");
>     }};
>     Assert.assertEquals(MVEL.eval("merchant-attributes", attribute), "abc");
> }
> ```

Unfortunately, I do not believe this is possible in mvel. Mvel, like any other computer language, has defined syntaxic rules that you have to follow while using it, and the use of a dash in an identifier does not follow these rules. If you have control over the context then I recommend to use the underscore instead of the dash in your variable name. Otherwise you can put the whole map inside a variable like this:
```
  public void test9() {
      Map attribute = new HashMap<String, String>() {{
          put("merchant-attributes", "abc");
      }};
      Assert.assertEquals(MVEL.eval("attributes[\"merchant-attributes\"]", Collections.singletonMap("attributes", attribute)), "abc");
  }
```
