### ISSUE TITLE
Sources jar contains only asm sources

### ISSUE THREAD

**Issue by sneudert** [mvel/mvel#349]
In mvel2-2.5.0.Final-sources.jar, only the sources of package org.mvel2.asm are contained (the sources of org.objectweb.asm with unsubstituted package name). this makes debugging awkward. 

- setting <createSourcesJar>false</createSourcesJar> for maven-shade-plugin fixes this.

**Comment by jdimeo** [comment]
I just noticed this too! Still present in 2.5.2

**Comment by jdimeo** [comment]
Related to changes in https://github.com/mvel/mvel/pull/330

**Comment by tkobayas** [comment]
Thank you for reporting, and sorry for replying late. It's surprising that  maven-shade-plugin creates a source jar which contains only dependencies' sources, not the project sources. As @sneudert wrote, setting `<createSourcesJar>false</createSourcesJar>` produces a source jar with the project source codes (but without the relocated asm sources).

I'll investigate if I can create a source jar contains both sources.

**Comment by tkobayas** [comment]
Maven mailing list greatly helped :)
https://lists.apache.org/thread/47bq292myz44rr0j8g75t2lpnvbs93fp

We just need to change the order of `maven-source-plugin` and `maven-shade-plugin`.

Filed a PR : https://github.com/mvel/mvel/pull/358

**Comment by tkobayas** [comment]
Fixed by https://github.com/mvel/mvel/pull/358
