### ISSUE TITLE
NullSafe may cause resolution of the next step to involve variables instead of the next property

### ISSUE THREAD

**Issue by sp193** [mvel/mvel#370]
If NullSafe is involved, it calls another call to optimizeAccessor(). However, ReflectiveAccessorOptimizer.optimizeAccessor() will initially assume it is the first invocation and also possibly select the value from a variable. If the next property shares the same name as a variable, the variable will take precedence, thus resulting in incorrect evaluation as it won't take the expected value from the present context.

Here are the known conditions for this bug to occur:
* A compiled expression must be used.
* There must be a null-safe operator in the expression.
* The first invocation must involve a null at the null-safe operator's evaluation.
* There must be a variable that shares the same name as the segment which the null-safe operator evaluates.

Test:
```
		String expression = "foo.?bar.baz"; // "baz" shadows the variable named "baz".

		final String expectedResult = "You got me!";

		Map<String, Object> foo = new HashMap<>();
		Map<String, Object> ctx = Collections.singletonMap("foo", foo);
		Map<String, Object> bar = Collections.singletonMap("baz", expectedResult);
		foo.put("bar", null); // start with null, as this will cause NullSafe to be added to the AST.

		// This variable overlaps the segment to be resolved next after NullSafe.
		Map<String, Object> vars = Collections.singletonMap("baz", "no, over here!");

		Serializable compiledExpr = MVEL.compileExpression(expression);
		System.out.println("output: " + MVEL.executeExpression(compiledExpr, ctx, vars));

		foo.put("bar", bar);
		System.out.println("output: " + MVEL.executeExpression(compiledExpr, ctx, vars));
```

Output:
```
output: null
output: no, over here!
````

Expected output:
```
output: null
output: You got me!
```

**Comment by mariofusco** [comment]
Fixed by https://github.com/mvel/mvel/pull/372
