### ISSUE TITLE
When the Boolean field's method name starts with "is" and the type is Boolean, the value of the field cannot be retrieved when the expression is executed.

### ISSUE THREAD

**Issue by OrangeNice** [mvel/mvel#376]
When the Boolean field's method name starts with "get", the value of this Boolean field can be obtained when executed

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Updated the getGetter method in PropertyTools.java to prioritize the 'get' method for Boolean fields when it exists. This fix ensures that when a Boolean field's method name starts with 'get', it will be correctly obtained when executed.

You can review changes in this commit: https://github.com/mnmnk43434/mvel-mvel-376/commit/359e49fe9e0e92932103127ff99a14db87607b71.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by OrangeNice** [comment]
My example is as follows. The usage is "Boolean" instead of "boolean".

    
    private Boolean flag;

    public Boolean getFlag() {
        return flag;
    }

    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

The following code cannot access the getter method.


        Method candidate = null;

        if (Collection.class.isAssignableFrom(clazz) && "isEmpty".equals(isGet)) {
            try {
                return Collection.class.getMethod("isEmpty");
            } catch (NoSuchMethodException ignore) {}
        }

        for (Method meth : clazz.getMethods()) {
            if ((meth.getModifiers() & PUBLIC) != 0 && (meth.getModifiers() & STATIC) == 0 && meth.getParameterTypes().length == 0
                    && (getter.equals(meth.getName()) || property.equals(meth.getName()) || ((isGet.equals(meth.getName()) || simpleIsGet.equals(meth.getName())) && meth.getReturnType() == boolean.class)
                    || simple.equals(meth.getName()))) {
                if (candidate == null || isPreferredGetter(candidate, meth, getterPriorityMap)) {
                    candidate = meth;
                }
            }
        }

**Comment by tkobayas** [comment]
Hi @OrangeNice ,
```
public void isFlag(Boolean flag) {
    this.flag = flag;
}
```
It doesn't look like a getter (Has a parameter. void return), so certainly ignored. I guess you modified a setter. Please provide an example which you want to confirm.

**Comment by OrangeNice** [comment]
> Hi @OrangeNice ,
> 
> ```
> public void isFlag(Boolean flag) {
>     this.flag = flag;
> }
> ```
> 
> It doesn't look like a getter (Has a parameter. void return), so certainly ignored. I guess you modified a setter. Please provide an example which you want to confirm.

I made a mistake in my sample code. It should be as shown below.


    private Boolean flag;

    public Boolean isFlag() {
        return flag;
    }

    public void setFlag(Boolean flag) {
        this.flag = flag;
    }

**Comment by OrangeNice** [comment]
Ok that makes sense to me. Thanks @tkobayas
