### ISSUE TITLE
MVEL Guide may be deleted from WikiSource

### ISSUE THREAD

**Issue by adarro** [mvel/mvel#95]
Not sure where to post this or how big of an issue or current it is, but the language guide linked [Guide](https://en.wikisource.org/wiki/MVEL_Language_Guide) in the readme is pending deletion from wikisource.  Apparently it was ported to Wikipedia which rejected it under 'Not a Guide' and ported it to WikiSource, where it may be deleted due to copyright. (Document is listed as (defunct) Codehaus holding the copyright). Perhaps making it a github page would be helpful as this is the only real reference I've seen documenting the language.
[Propossed Delete](https://en.wikisource.org/wiki/Wikisource:Proposed_deletions#MVEL_Language_Guide)

**Comment by d4ve** [comment]
+1. Could the owner of this project please copy these docs to Github? They're really essential.

**Comment by fsparv** [comment]
Now deleted from wikisource....

**Comment by lichtin** [comment]
See issue #101

**Comment by adarro** [comment]
#101 Fixes this just fine.  Thanks.
